# Generated by Django 3.2.6 on 2021-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=150, verbose_name='Function')),
                ('plot', models.ImageField(blank=True, editable=False, upload_to='plots/', verbose_name='Plot')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Interval t, in days')),
                ('steep', models.PositiveIntegerField(default=1, verbose_name='Steep dt, in hours')),
                ('processing', models.DateTimeField(auto_now=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-processing'],
            },
        ),
    ]
